AWSTemplateFormatVersion: 2010-09-09
Resources:
  FilaTeste:
    Type: "AWS::SQS::Queue"
    Properties: 
      QueueName: "FilaTeste"
  AlarmTeste:
    Type: "AWS::CloudWatch::Alarm"
    Properties: 
      AlarmActions:
        - !Sub "arn:aws:sns:sa-east-1:${AWS::AccountId}:testando"
      AlarmDescription: "Alerta mensagem na fila"
      AlarmName: "AlertaMensagem"
      Metrics:
         - Expression: "m2-m1"
           Id: "e1"
           Label: "ChangeInAmountVisible"
           ReturnData: true
         - Id: "m1"
           Label: "MessagesVisibleMin"
           MetricStat:
            Metric: 
              Dimensions:
                - Name: "QueueName"
                  Value: 
                    Fn::GetAtt: 
                    - "FilaTeste"
                    - "QueueName"
              MetricName: "ApproximateNumberOfMessagesVisible"
              Namespace: "AWS/SQS"
            Period: "300"
            Stat: "Minimum"
            Unit: "Count"
           ReturnData: false
         - Id: "m2"
           Label: "MessagesVisibleMax"
           MetricStat:
            Metric: 
              Dimensions:
                - Name: "QueueName"
                  Value: 
                    Fn::GetAtt: 
                    - "FilaTeste"
                    - "QueueName"
              MetricName: "ApproximateNumberOfMessagesVisible"
              Namespace: "AWS/SQS"
            Period: "300"
            Stat: "Maximum"
            Unit: "Count"
           ReturnData: false   
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      Threshold: 1
      DatapointsToAlarm: 1
      EvaluationPeriods: 1