AWSTemplateFormatVersion: 2010-09-09
Resources:
  Teste:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: Teste
      FifoTopic: false
      Subscription:
        - Endpoint: igorcsaraiva@hotmail.com
          Protocol: email
      TopicName: testando
  mysnspolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action: 
             - "sns:Publish"
            Resource: !Ref Teste
            Condition:
              ArnEquals:
                AWS:SourceArn: 
                 - !Sub 'arn:aws:cloudwatch:sa-east-1:${AWS::AccountId}:alarm:CriadoNaMao'
                 - !Sub 'arn:aws:cloudwatch:sa-east-1:${AWS::AccountId}:alarm:AlertaMensagem'
      Topics:
        - !Ref Teste